# theme: jekyll-theme-minimal
remote_theme: "mmistakes/minimal-mistakes@4.16.6"
plugins: [jekyll-include-cache]
minimal_mistakes_skin: "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
title: "My Awesome Site"
name: "Michael Rose"
